### ISSUE TITLE
Allow settings menu with unlocked fps option to show up without RTX enabled for unsupported cards

### ISSUE THREAD

**Issue by PyroJay4** [DarioSamo/sm64rt#34] opened 2021-08-03 15:18 UTC
thats it i guess 
idk

**Comment by DarioSamo** [comment] 2021-08-04 01:13
The high framerate option by design only works with the RT renderer because it sends the data very differently compared to what the other render APIs do.

For the high framerate option to work on the other renderers, you'd need to reimplement them to all do interpolation.

This is really beyond the scope of the project for now, so unless I misunderstood your request, I'll close this issue.

**Closed by DarioSamo** 2021-08-04 01:13 UTC
